name: Sync upstream → original

on:
  schedule:
    - cron: "0 5 * * 1"   # Mondays 05:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out my fork
      - name: Checkout fork
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4 pinned
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Add upstream and fetch
      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/ed-donner/agents.git || true
          git fetch upstream --tags --prune

      # 3) Make 'original' exactly match upstream/main
      - name: Mirror upstream/main → original
        run: |
          git checkout -B original upstream/main
          git push origin original --force
